# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - config-promote-api

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/main_config-promote-api.yml'
      - 'src/config-promote-api/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PROJECT_PATH: './src/config-promote-api/config-promote-api.csproj'
  AZURE_FUNCTIONAPP_PUBLISH_PATH: './artifacts/config-promote-api'
  DOTNET_VERSION: '10.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore and publish Function App'
        shell: bash
        run: |
          dotnet restore '${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }}'
          dotnet publish '${{ env.AZURE_FUNCTIONAPP_PROJECT_PATH }}' \
            --configuration Release \
            --no-restore \
            --output '${{ env.AZURE_FUNCTIONAPP_PUBLISH_PATH }}'
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24375A03171549A3B9870DB7974AAB7F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_96B089F6A4E6473395CD83A8C21FD580 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_12B76D9EABC642EA8043A89ECC6AE1B3 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'config-promote-api'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PUBLISH_PATH }}'
          
