# Simple workflow for deploying static content to GitHub Pages
name: Update Config Browser

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install wasm tools
        run: dotnet workload install wasm-tools

      - name: Restore projects
        run: |
          dotnet restore ./src/config-browser/config-browser.csproj

      - name: Publish browser app
        working-directory: ./src/config-browser
        run: dotnet publish ./config-browser.csproj -c Release --no-restore -o ../../artifacts/config-browser

      - name: Configure published site
        run: |
          sed -i 's|<base href="/" />|<base href="/${{ github.event.repository.name }}/" />|' ./artifacts/config-browser/wwwroot/index.html
          cp ./artifacts/config-browser/wwwroot/index.html ./artifacts/config-browser/wwwroot/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifacts/config-browser/wwwroot'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
